name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: version-check
        uses: EndBug/version-check@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - id: deploy-to-heroku
        if: steps.check.outputs.changed == 'true'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'mdn-bcd-collector'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
